spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 2111703401
    url: jdbc:mysql://47.107.108.7/tests?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    open-in-view: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
server:
  servlet:
    context-path: /sell
  port: 8080
wechat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: 47ccc303338cee6e62894fxxxxxxxxxxx
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ
project-url:
   wechat-mp-authorize: http://127.0.0.1:8080
   sell: http://127.0.0.1:8080
   wechat-open-authorize: http://127.0.0.1:8080